version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update -y && apt-get install python3-pip -y
      - pip3 install pipenv --user
      - pipenv install aws-sam-cli

  build:
    commands:
      - pipenv run sam build --use-container
      - pipenv run sam package --s3-bucket $BucketName --s3-prefix SAMArtifacts --output-template-file sam_output.yml

artifacts:
  type: zip
  files:
    - sam_output.yml
