AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rpg-sheet-api

  Sample SAM Template for rpg-sheet-api

Parameters:
  Environment:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.7
    Handler: index.handler
    Timeout: 90
    Environment:
      Variables:
        character_table_name: !Sub ${Environment}CharactersTable

Resources:

  CharactersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${Environment}CharactersTable
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${Environment}RestApi
      EndpointConfiguration: EDGE
      Cors:
        AllowHeaders: "'Content-Type,Accept'"
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,DELETE,PUT,OPTIONS'"
      StageName: dev
  
  GetClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}GetCharacter
      CodeUri: './handlers/get_character'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Resource: '*'
              Action:
                - dynamodb:GetItem
                - dynamodb:Scan
                - cognito-idp:AdminGetUser
      Events:
        RestApi:
          Type: Api
          Properties:
            Method: GET
            Path: /character
            RestApiId: !Ref RestApi  
  
  PutClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}GetCharacter
      CodeUri: './handlers/get_character'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Resource: '*'
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
      Events:
        RestApi:
          Type: Api
          Properties:
            Method: PUT
            Path: /character
            RestApiId: !Ref RestApi  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
